learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls', namespace="learning_logs")),
    path('users/', include('users.urls', namespace='users'))
]

learning_logs/urls.py
"""Define URL ptterms for learning_Logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'

urlpatterns = [
    #   Home Page.
    path('', views.index, name='index'),

    #   Show All Topics
    path('topics/', views.topics, name='topics'),

    #   Detail page for a single Topic
    path('topics/<int:topic_id>/', views.topic, name="topic"),

    #   Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),

    #   Page for adding new Entry
    path('new_entry/<int:topic_id>', views.new_entry, name="new_entry"),

    #   Page For Editing An Entry
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Define URl Patterns for Users"""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    # Login Page
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    
    # Logout Page
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),

    # Registration Page
    path('register/', views.register, name='register')
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    """A topic the User is Learning About"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return A string rep of the model"""
        return self.text
    
class Entry(models.Model):
     """Something specific about a topic"""
     topic = models.ForeignKey('Topic', on_delete=models.CASCADE)
     text = models.TextField()
     date_added = models.DateTimeField(auto_now_add=True)

     class Meta:
         verbose_name_plural = 'entries'

     def __str__(self):
         """Return a string rep of the Model."""
         return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={"cols": 80})}
                  

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse 
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm
# Create your views here.

def index(request):
    """The home page for Learning log"""
    return render(request, "learning_logs/index.html")

@login_required
def topics(request):
    """Shows All Topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request,'learning_logs/topics.html', context) 

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    # Make Sure the topic belongd to the current user.
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by("-date_added")
    context = {"topic": topic, "entries": entries}
    return render(request, "learning_logs/topic.html", context)

@login_required
def new_topic(request):
    """Add a new Topic"""
    if request.method != "POST":
        #  No Data submitted; Create A Blank Form.
        form = TopicForm()
    else:
        #  POST data submited; process Data.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            form.save()
            return HttpResponseRedirect(reverse("learning_logs:topics"))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add A New Entry For A Particular Topic."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != "POST":
        #  No Data Submitted; Create A Blank Form.
        form = EntryForm()
    else:
        #  POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {"topic": topic, "form":form }
    return render(request, "learning_logs/new_entry.html", context)

@login_required
def edit_entry(request, entry_id):
    """Edit an Existing Entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        #  Initial request; Pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        #  POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    
    context = {'entry': entry, 'topic':topic, 'form':form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
# def logout_view(request):
#     """Log the User Out."""
#     logout(request)
    #return redirect('users:logged_out')

def register(request):
    """Register A New User"""
    if request.method != 'POST':
        #  Display Blank Registration Form.
        form = UserCreationForm()
    else:
        # Process Completed Form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the User in and then redirect to home page
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'learning_log_project/staticfiles/styles.css' %}">
        <title>LEARNING LOG</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>

    <body style="background-color: burlywood;">

        <!-- Static Navbar -->
        <nav class="navbar navbar-default navbar-static-top" style="background-color:black; font-family: Impact; font-size:larger;">
            <div class="container">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'learning_logs:index' %}" style="color:white ;">
                    LEARNING LOG
                </a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'learning_logs:topics' %}" style="color: white;">TOPICS</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a style="color: white;">HELLO, {{ user.username }}.</a></li>
                            <li><a href="{% url 'users:logout' %}" style="color: white;">LOG OUT</a></li>
                        {% else %}
                            <li><a href="{% url 'users:register' %}" style="color: white;">REGISTER</a></li>
                            <li><a href="{% url 'users:login' %}" style="color: white;">LOG IN</a></li>
                        {% endif %}
                    </ul>
                </div><!--/.nav-collapse -->
            
            </div>
        </nav> 

        <div class="container" style="color: black;">

            <div class="page-header" style="color: black;">
                {% block header %}{% endblock header %}
            </div>
            <div style="color: black;">
                {% block content %}{% endblock content %}
            </div>
        </div> <!--/container-->
    </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h3>Edit Entry:</h3>
{% endblock header %}

{% block content %}

    <h4><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h4>

    <form class="form" action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        
        {% bootstrap_form form %}

        {% buttons %}
        <button class="btn btn-primary" name="Submit">Save Changes</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{%  extends "learning_logs/base.html"   %}

{% block header %}
    <div class="jumbotron" style="border-style: double; border-radius:20px; border-width: 7px; border-color:black; background-color:darkgrey;" >
        <h2 style="font-family:Verdana, Geneva; font-weight:bold; font-size: xx-large; color:black;">TRACK YOUR LEARNING...</h2>
    </div>
{% endblock header %}

{% block content %}
    <h3 style="font-family: Verdana, Geneva, Tahoma; font-size: 30px;" >
        <a href="{% url 'users:register' %}" style="color: darkslategrey;">REGISTER AN ACCOUNT</a> To Make Your Own Learning Log, And List The Topics You're Learning About.
    </h3>
    <h3 style="font-family: Verdana, Geneva, Tahoma; font-size:30px;">
        Whenever You Learn Something New About A Topic, Make An Entry Summarizing What You've Learned.
    </h3>
{%  endblock content  %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h3>Add A New Entry:</h3>
{% endblock header %}

{% block content %}

    <h4><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic}}</a></h4>

    <form class="form" action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        
        {% bootstrap_form form %}

        {% buttons %}
        <button class="btn btn-primary" name="Submit">Add entry</button>
        {% endbuttons %}
    
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add A New Topic:</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
        <button name="submit" class="btn btn-primary">Add Topic</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <h1 style="font-weight: bold; font-family: Georgia, 'Times New Roman';">{{ topic }}</h1>
{% endblock header %}

{% block content %}
    <h3 style="font-family: 'Franklin Gothic Medium';">
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add New Entry</a>
    </h3>

    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    <small>
                        <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit Entry</a>
                    </small>
                </h3>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>
        </div><!-- panel -->
       
        {% empty %}
            There are no entries for this topic yet.
        {% endfor %}
    

    {% endblock content %}

learning_logs/templates/learning_logs/topics.html
{%  extends "learning_logs/base.html" %}

{% block header %}
    <h1 style="font-weight: bold; font-family: Georgia, 'Times New Roman';">TOPICS</h1>
{% endblock header %}

{% block content %}

<ul style="margin: 0; padding: 0; background-color: wheat; border-style: double; border-width: 6px;">
    {% for topic in topics %}
    <li style="display: block;">
        <h2 style="font-family: 'Franklin Gothic Medium';">
    </li>
    {% empty %}
    <li style="display: block;"><h2 style="font-family: 'Franklin Gothic Medium';">No Topics Have Been Added Yet...</h2></li>
    {% endfor %}
</ul>

<h2 style="font-family: 'Franklin Gothic Medium';"><a href="{% url 'learning_logs:new_topic' %}" style="color:darkred; text-decoration: none;" onmouseover="this.style.color='white'" onmouseout="this.style.color='#8b0000'">Add A New Topic?</a></h2>

{% endblock content %}

users/templates/users/logged_out.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p>You Have been Logged Out. Thanks For Visiting!</p>
{% endblock content %}

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">

<head>
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
</head>

<body>
{% block header %}
    <h2 style="color: teal;">Log In to Your Account.</h2>
{% endblock header %}

{% block content %}

    <form method="post" action="{% url 'users:login' %}" class="form" style="color: black;">
        {% csrf_token %}
        
        {% bootstrap_form form %}

        {% buttons %}
            <button name="Submit" class="btn btn-primary">Log In</button>
        {% endbuttons %}
    
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
    </form>

{% endblock content%}
</body>
</html>

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h3>REGISTER</h3>
{% endblock header %}

{% block content %}

    <form class="form"  method="post" action="{% url  'users:register' %}">
        {% csrf_token %}
        
        {% bootstrap_form form %}

        {% buttons %}
        <button class="btn btn-primary" name='submit'>REGISTER</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>
{% endblock content %}